/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BabyCribView {
  'id' : string,
  'numberOfCaregivers' : bigint,
  'name' : string,
  'reservedTimeSlots' : Array<ReservedTimeSlot>,
}
export interface Reservation {
  'id' : string,
  'startTime' : Time,
  'userId' : Principal,
  'cribId' : string,
  'serviceId' : string,
}
export interface ReservedTimeSlot { 'startTime' : Time, 'endTime' : Time }
export interface Service {
  'id' : string,
  'duration' : bigint,
  'name' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCrib' : ActorMethod<[string, string, bigint], undefined>,
  'addService' : ActorMethod<[string, string, bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelReservation' : ActorMethod<[Principal, string], undefined>,
  'getAllCribs' : ActorMethod<[], Array<BabyCribView>>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getAvailableServices' : ActorMethod<[], Array<Service>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCrib' : ActorMethod<[string], BabyCribView>,
  'getLoyaltyPoints' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserReservations' : ActorMethod<[Principal], Array<Reservation>>,
  'initializeCribs' : ActorMethod<[], undefined>,
  'initializeServices' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCrib' : ActorMethod<[string], undefined>,
  'reserveCrib' : ActorMethod<[Principal, string, string, Time], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'spendLoyaltyPoints' : ActorMethod<[Principal, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];