/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ReservedTimeSlot = IDL.Record({
  'startTime' : Time,
  'endTime' : Time,
});
export const BabyCribView = IDL.Record({
  'id' : IDL.Text,
  'numberOfCaregivers' : IDL.Nat,
  'name' : IDL.Text,
  'reservedTimeSlots' : IDL.Vec(ReservedTimeSlot),
});
export const Reservation = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'userId' : IDL.Principal,
  'cribId' : IDL.Text,
  'serviceId' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCrib' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelReservation' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'getAllCribs' : IDL.Func([], [IDL.Vec(BabyCribView)], ['query']),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getAvailableServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCrib' : IDL.Func([IDL.Text], [BabyCribView], ['query']),
  'getLoyaltyPoints' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserReservations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'initializeCribs' : IDL.Func([], [], []),
  'initializeServices' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCrib' : IDL.Func([IDL.Text], [], []),
  'reserveCrib' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, Time],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'spendLoyaltyPoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReservedTimeSlot = IDL.Record({ 'startTime' : Time, 'endTime' : Time });
  const BabyCribView = IDL.Record({
    'id' : IDL.Text,
    'numberOfCaregivers' : IDL.Nat,
    'name' : IDL.Text,
    'reservedTimeSlots' : IDL.Vec(ReservedTimeSlot),
  });
  const Reservation = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'userId' : IDL.Principal,
    'cribId' : IDL.Text,
    'serviceId' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCrib' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelReservation' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'getAllCribs' : IDL.Func([], [IDL.Vec(BabyCribView)], ['query']),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getAvailableServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCrib' : IDL.Func([IDL.Text], [BabyCribView], ['query']),
    'getLoyaltyPoints' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserReservations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'initializeCribs' : IDL.Func([], [], []),
    'initializeServices' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCrib' : IDL.Func([IDL.Text], [], []),
    'reserveCrib' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, Time],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'spendLoyaltyPoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };