/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'client' : null } |
  { 'professional' : null };
export interface Booking {
  'id' : string,
  'status' : BookingStatus,
  'clientId' : Principal,
  'date' : string,
  'address' : string,
  'serviceId' : string,
  'proId' : Principal,
  'totalPrice' : bigint,
  'timeSlot' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type ExternalBlob = Uint8Array;
export interface Language { 'language' : string, 'proficiency' : string }
export interface ProProfile {
  'id' : Principal,
  'bio' : string,
  'atHomeService' : boolean,
  'city' : string,
  'languages' : Array<Language>,
  'weeklyAvailability' : WeeklyAvailability,
  'slogan' : string,
  'subscriptionStatus' : boolean,
  'isVerified' : boolean,
  'profileStatus' : ProfileStatus,
  'category' : string,
  'radius' : bigint,
  'galleries' : Array<ExternalBlob>,
  'brandName' : string,
  'phone' : string,
  'trialStartDate' : [] | [Time],
  'mainPhoto' : [] | [ExternalBlob],
  'galleryPhotos' : Array<ExternalBlob>,
  'minBookingLeadTime' : bigint,
}
export type ProfileStatus = { 'published' : null } |
  { 'draft' : null };
export interface Service {
  'id' : string,
  'duration' : bigint,
  'name' : string,
  'badges' : Array<string>,
  'beforeAfterPhotos' : Array<ExternalBlob>,
  'price' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TimeSlot { 'startTime' : bigint, 'endTime' : bigint }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'appRole' : [] | [AppUserRole], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyAvailability {
  'tuesday' : Array<TimeSlot>,
  'wednesday' : Array<TimeSlot>,
  'saturday' : Array<TimeSlot>,
  'thursday' : Array<TimeSlot>,
  'sunday' : Array<TimeSlot>,
  'friday' : Array<TimeSlot>,
  'monday' : Array<TimeSlot>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetAllBookings' : ActorMethod<[], Array<Booking>>,
  'adminGetAllPros' : ActorMethod<[], Array<ProProfile>>,
  'adminGetMetrics' : ActorMethod<
    [],
    {
      'totalBookings' : bigint,
      'totalRegisteredUsers' : bigint,
      'totalActivePros' : bigint,
    }
  >,
  'adminValidatePro' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBookingRequest' : ActorMethod<
    [Principal, string, string, string, string],
    string
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrUpdateProProfile' : ActorMethod<[ProProfile], undefined>,
  'filterProsByLocation' : ActorMethod<
    [number, number, bigint, [] | [string]],
    Array<ProProfile>
  >,
  'getBooking' : ActorMethod<[string], [] | [Booking]>,
  'getBookingsByProfessional' : ActorMethod<[Principal], Array<Booking>>,
  'getBookingsByUser' : ActorMethod<
    [Principal, [] | [BookingStatus]],
    Array<Booking>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProProfile' : ActorMethod<[Principal], ProProfile>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'publishProfile' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingStatus' : ActorMethod<[string, BookingStatus], undefined>,
  'updateGallery' : ActorMethod<
    [[] | [ExternalBlob], Array<ExternalBlob>],
    undefined
  >,
  'updateServices' : ActorMethod<[Array<Service>], undefined>,
  'updateWeeklyAvailability' : ActorMethod<[WeeklyAvailability], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];