/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : BookingStatus,
  'clientId' : IDL.Principal,
  'date' : IDL.Text,
  'address' : IDL.Text,
  'serviceId' : IDL.Text,
  'proId' : IDL.Principal,
  'totalPrice' : IDL.Nat,
  'timeSlot' : IDL.Text,
});
export const Language = IDL.Record({
  'language' : IDL.Text,
  'proficiency' : IDL.Text,
});
export const TimeSlot = IDL.Record({
  'startTime' : IDL.Nat,
  'endTime' : IDL.Nat,
});
export const WeeklyAvailability = IDL.Record({
  'tuesday' : IDL.Vec(TimeSlot),
  'wednesday' : IDL.Vec(TimeSlot),
  'saturday' : IDL.Vec(TimeSlot),
  'thursday' : IDL.Vec(TimeSlot),
  'sunday' : IDL.Vec(TimeSlot),
  'friday' : IDL.Vec(TimeSlot),
  'monday' : IDL.Vec(TimeSlot),
});
export const ProfileStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const ProProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'atHomeService' : IDL.Bool,
  'city' : IDL.Text,
  'languages' : IDL.Vec(Language),
  'weeklyAvailability' : WeeklyAvailability,
  'slogan' : IDL.Text,
  'subscriptionStatus' : IDL.Bool,
  'isVerified' : IDL.Bool,
  'profileStatus' : ProfileStatus,
  'category' : IDL.Text,
  'radius' : IDL.Nat,
  'galleries' : IDL.Vec(ExternalBlob),
  'brandName' : IDL.Text,
  'phone' : IDL.Text,
  'trialStartDate' : IDL.Opt(Time),
  'mainPhoto' : IDL.Opt(ExternalBlob),
  'galleryPhotos' : IDL.Vec(ExternalBlob),
  'minBookingLeadTime' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AppUserRole = IDL.Variant({
  'client' : IDL.Null,
  'professional' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : IDL.Opt(AppUserRole),
  'name' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'beforeAfterPhotos' : IDL.Vec(ExternalBlob),
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'adminGetAllPros' : IDL.Func([], [IDL.Vec(ProProfile)], ['query']),
  'adminGetMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalBookings' : IDL.Nat,
          'totalRegisteredUsers' : IDL.Nat,
          'totalActivePros' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'adminValidatePro' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBookingRequest' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrUpdateProProfile' : IDL.Func([ProProfile], [], []),
  'filterProsByLocation' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Vec(ProProfile)],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getBookingsByProfessional' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByUser' : IDL.Func(
      [IDL.Principal, IDL.Opt(BookingStatus)],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProProfile' : IDL.Func([IDL.Principal], [ProProfile], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'publishProfile' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
  'updateGallery' : IDL.Func(
      [IDL.Opt(ExternalBlob), IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
  'updateServices' : IDL.Func([IDL.Vec(Service)], [], []),
  'updateWeeklyAvailability' : IDL.Func([WeeklyAvailability], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : BookingStatus,
    'clientId' : IDL.Principal,
    'date' : IDL.Text,
    'address' : IDL.Text,
    'serviceId' : IDL.Text,
    'proId' : IDL.Principal,
    'totalPrice' : IDL.Nat,
    'timeSlot' : IDL.Text,
  });
  const Language = IDL.Record({
    'language' : IDL.Text,
    'proficiency' : IDL.Text,
  });
  const TimeSlot = IDL.Record({ 'startTime' : IDL.Nat, 'endTime' : IDL.Nat });
  const WeeklyAvailability = IDL.Record({
    'tuesday' : IDL.Vec(TimeSlot),
    'wednesday' : IDL.Vec(TimeSlot),
    'saturday' : IDL.Vec(TimeSlot),
    'thursday' : IDL.Vec(TimeSlot),
    'sunday' : IDL.Vec(TimeSlot),
    'friday' : IDL.Vec(TimeSlot),
    'monday' : IDL.Vec(TimeSlot),
  });
  const ProfileStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const ProProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'atHomeService' : IDL.Bool,
    'city' : IDL.Text,
    'languages' : IDL.Vec(Language),
    'weeklyAvailability' : WeeklyAvailability,
    'slogan' : IDL.Text,
    'subscriptionStatus' : IDL.Bool,
    'isVerified' : IDL.Bool,
    'profileStatus' : ProfileStatus,
    'category' : IDL.Text,
    'radius' : IDL.Nat,
    'galleries' : IDL.Vec(ExternalBlob),
    'brandName' : IDL.Text,
    'phone' : IDL.Text,
    'trialStartDate' : IDL.Opt(Time),
    'mainPhoto' : IDL.Opt(ExternalBlob),
    'galleryPhotos' : IDL.Vec(ExternalBlob),
    'minBookingLeadTime' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AppUserRole = IDL.Variant({
    'client' : IDL.Null,
    'professional' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : IDL.Opt(AppUserRole),
    'name' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'beforeAfterPhotos' : IDL.Vec(ExternalBlob),
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'adminGetAllPros' : IDL.Func([], [IDL.Vec(ProProfile)], ['query']),
    'adminGetMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalBookings' : IDL.Nat,
            'totalRegisteredUsers' : IDL.Nat,
            'totalActivePros' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'adminValidatePro' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBookingRequest' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrUpdateProProfile' : IDL.Func([ProProfile], [], []),
    'filterProsByLocation' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Vec(ProProfile)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getBookingsByProfessional' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByUser' : IDL.Func(
        [IDL.Principal, IDL.Opt(BookingStatus)],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProProfile' : IDL.Func([IDL.Principal], [ProProfile], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'publishProfile' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
    'updateGallery' : IDL.Func(
        [IDL.Opt(ExternalBlob), IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
    'updateServices' : IDL.Func([IDL.Vec(Service)], [], []),
    'updateWeeklyAvailability' : IDL.Func([WeeklyAvailability], [], []),
  });
};

export const init = ({ IDL }) => { return []; };